// <auto-generated />
namespace HTTP_5212_Passion_Project_RX_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createNewTablesV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createNewTablesV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202202140404190_createNewTablesV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
